name: Sync autoclear-chatgpt-history to adamlui/autoclear-chatgpt-history/greasemonkey

on:
  push:
    branches: [ master, main ]
    paths:
      - 'autoclear-chatgpt-history/**'

jobs:
  build:
    if: github.event.commits[0].committer.username != 'auto-sync-bot'
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/chatgpt-userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-userscripts
          path: adamlui/chatgpt-userscripts

      - name: Checkout adamlui/autoclear-chatgpt-history
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/autoclear-chatgpt-history
          path: adamlui/autoclear-chatgpt-history

      - name: Sync adamlui/chatgpt-userscripts/autoclear-chatgpt-history to adamlui/autoclear-chatgpt-history/greasemonkey
        run: rsync -av --delete ${{ github.workspace }}/adamlui/chatgpt-userscripts/autoclear-chatgpt-history/ ${{ github.workspace }}/adamlui/autoclear-chatgpt-history/greasemonkey/

      - name: Push to adamlui/autoclear-chatgpt-history
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@userscripts.co
          commit_message: '${{ github.event.head_commit.message }} â†ž [auto-sync from `adamlui/chatgpt-userscripts`]'
          file_pattern: '*'
          repository: adamlui/autoclear-chatgpt-history