name: Sync autoclear-chatgpt-history to adamlui/autoclear-chatgpt-history/greasemonkey

on:
  push:
    branches:
      - master
    paths:
      - 'autoclear-chatgpt-history/**'
    if: 'github.event.head_commit.committer.username != "auto-sync-bot"'

jobs:
  sync-autoclear-chatgpt-history:
    runs-on: ubuntu-latest
    steps:

      # Checkout adamlui/chatgpt-userscripts
      - name: Checkout adamlui/chatgpt-userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-userscripts
          path: adamlui/chatgpt-userscripts

      # Checkout adamlui/autoclear-chatgpt-history
      - name: Checkout adamlui/autoclear-chatgpt-history
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/autoclear-chatgpt-history
          path: adamlui/autoclear-chatgpt-history

      # Sync adamlui/chatgpt-userscripts/autoclear-chatgpt-history to adamlui/autoclear-chatgpt-history/greasemonkey
      - name: Sync autoclear-chatgpt-history
        run: rsync -av --delete ${{ github.workspace }}/adamlui/chatgpt-userscripts/autoclear-chatgpt-history/ ${{ github.workspace }}/adamlui/autoclear-chatgpt-history/greasemonkey/
      
      # Push to adamlui/autoclear-chatgpt-history
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@userscripts.co
          commit_message: '${{ github.event.head_commit.message }} â†ž [auto-sync from `adamlui/chatgpt-userscripts`]'
          file_pattern: '*'
          repository: adamlui/autoclear-chatgpt-history