name: Sync (duckduckgpt/ to KudoAI/duckduckgpt/) && (duckduckgpt/greasemonkey/ to adamlui/userscripts/chatgpt/duckduckgpt/)

on:
  push:
    branches: main
    paths: duckduckgpt/**

jobs:
  build:
    if: (github.repository == 'adamlui/chatgpt-apps') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Checkout KudoAI/duckduckgpt
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: KudoAI/duckduckgpt
          path: KudoAI/duckduckgpt

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Sync docs between root & /greasemonkey
        run: |
          shopt -s globstar
          cd ${{ github.workspace }}/adamlui/chatgpt-apps/duckduckgpt

          # Sync LICENSE.md
          root_license_modified=$(git log -1 --format="%ct" -- "LICENSE.md")
          gm_license_modified=$(git log -1 --format="%ct" -- "greasemonkey/LICENSE.md")
          if (( root_license_modified > gm_license_modified )) ; then cp -f "LICENSE.md" "greasemonkey/LICENSE.md"
          elif (( gm_license_modified > root_license_modified )) ; then cp -f "greasemonkey/LICENSE.md" "LICENSE.md" ; fi

          # Sync other docs
          for file in docs/**/*.md; do
            relative_path=${file#"docs/"}
            root_doc="docs/$relative_path"
            root_doc_modified=$(git log -1 --format="%ct" -- "$root_doc")
            gm_doc="greasemonkey/docs/$relative_path"
            gm_doc_modified=$(git log -1 --format="%ct" -- "$gm_doc")
            if (( root_doc_modified > gm_doc_modified )) ; then cp -f "$root_doc" "$gm_doc"
            elif (( gm_doc_modified > root_doc_modified )) ; then cp -f "$gm_doc" "$root_doc" ; fi
          done

      - name: Sync duckduckgpt/ to KudoAI/duckduckgpt/
        run: |
          rsync -avhr --delete --filter={'P /.*','P /package*.json'} \
            ${{ github.workspace }}/adamlui/chatgpt-apps/duckduckgpt/ \
            ${{ github.workspace }}/KudoAI/duckduckgpt/

      - name: Sync duckduckgpt/greasemonkey/ to adamlui/userscripts/chatgpt/duckduckgpt/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/chatgpt-apps/duckduckgpt/greasemonkey/ \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/duckduckgpt/

      - name: Push to adamlui/chatgpt-apps
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@kudoai.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/chatgpt-apps`]'
          file_pattern: 'duckduckgpt/**'
          repository: adamlui/chatgpt-apps

      - name: Push to KudoAI/duckduckgpt
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@kudoai.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/chatgpt-apps`]'
          file_pattern: '**'
          repository: KudoAI/duckduckgpt

      - name: Push to adamlui/userscripts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_email: auto-sync@kudoai.com
          commit_message: '${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/chatgpt-apps`]'
          file_pattern: 'chatgpt/duckduckgpt/**'
          repository: adamlui/userscripts
