name: Sync /chatgpt-widescreen/chrome/extension/ to /chatgpt-widescreen/(edge|opera)/extension/, then /chatgpt-widescreen/chrome/extension/_locales/ to /chatgpt-widescreen/greasemonkey/_locales/, then /chatgpt-widescreen/ to adamlui/chatgpt-widescreen/, then /chatgpt-widescreen/greasemonkey/ to adamlui/userscripts/chatgpt/chatgpt-widescreen/

on:
  push:
    branches: main
    paths: chatgpt-widescreen/chrome/**

jobs:
  build:
    if: (github.repository == 'adamlui/chatgpt-apps') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps

      - name: Checkout adamlui/chatgpt-widescreen
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-widescreen
          path: adamlui/chatgpt-widescreen

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Sync /chatgpt-widescreen/chrome/extension/ to /chatgpt-widescreen/(edge|opera)/extension/
        run: |
          for browser in edge opera
          do
            rsync -avhr --delete \
              "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen/chrome/extension/" \
              "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen/$browser/extension/"
          done

      - name: Sync /chatgpt-widescreen/chrome/extension/_locales/ to /chatgpt-widescreen/greasemonkey/_locales/
        run: |
          rsync -avhr --delete \
            "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen/chrome/extension/_locales/" \
            "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen/greasemonkey/_locales"

      - name: Sync /chatgpt-widescreen/ to adamlui/chatgpt-widescreen/
        run: |
          rsync -avhr --delete --filter={'P /.*','P /package*.json'} \
            ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen/ \
            ${{ github.workspace }}/adamlui/chatgpt-widescreen/

      - name: Sync /chatgpt-widescreen/greasemonkey/ to adamlui/userscripts/chatgpt/chatgpt-widescreen/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-widescreen/greasemonkey/ \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-widescreen/

      - name: Push to adamlui/chatgpt-apps
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: --force
          add_options: --all
          commit_user_email: auto-sync@kudoai.com
          commit_message: "${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/chatgpt-apps`]"
          file_pattern: "chatgpt-widescreen/**"
          repository: adamlui/chatgpt-apps

      - name: Push to adamlui/chatgpt-widescreen
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: --force
          add_options: --all
          commit_user_email: auto-sync@kudoai.com
          commit_message: "${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/chatgpt-apps`]"
          file_pattern: "**"
          repository: adamlui/chatgpt-widescreen

      - name: Push to adamlui/userscripts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: --force
          add_options: --all
          commit_user_email: auto-sync@kudoai.com
          commit_message: "${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/chatgpt-apps`]"
          file_pattern: "chatgpt/chatgpt-widescreen/**"
          repository: adamlui/userscripts
