name: Sync perplexity-omnibox/ to adamlui/perplexity-omnibox/
on:
  push:
    branches: [main]
    paths: [perplexity-omnibox/**]

jobs:
  build:
    if: (github.repository == 'adamlui/ai-web-extensions') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    env:
      TZ: PST8PDT

    steps:

      - name: Checkout adamlui/ai-web-extensions
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/ai-web-extensions
          path: adamlui/ai-web-extensions

      - name: Checkout adamlui/perplexity-omnibox
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/perplexity-omnibox
          path: adamlui/perplexity-omnibox

      - name: Sync perplexity-omnibox/ to adamlui/perplexity-omnibox/
        run: |
          rsync -avhr --delete --filter={'P /.*','P /eslint*','P /package*.json'} \
            ${{ github.workspace }}/adamlui/ai-web-extensions/perplexity-omnibox/ \
            ${{ github.workspace }}/adamlui/perplexity-omnibox/

      - name: Escape backticks in commit msg
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "ESCAPED_MSG<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MSG" | sed 's/`/\`/g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Config committer
        run: |
          gpg --batch --import <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
          git config --global commit.gpgsign true
          git config --global user.name "kudo-sync-bot"
          git config --global user.email "auto-sync@kudoai.com"
          git config --global user.signingkey "${{ secrets.GPG_PRIVATE_ID }}"

      - name: Push changes to adamlui/ai-web-extensions
        run: |
          cd ${{ github.workspace }}/adamlui/ai-web-extensions
          git pull # again to sync w/ concurrent workflow updates
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`adamlui/ai-web-extensions\`]" || true
          git push

      - name: Push changes to adamlui/perplexity-omnibox
        run: |
          cd ${{ github.workspace }}/adamlui/perplexity-omnibox
          git pull # again to sync w/ concurrent workflow updates
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`adamlui/ai-web-extensions\`]" || true
          git push
