name: Sync _locales/* between chatgpt-auto-continue/<chrome|firefox>/extension/, then chatgpt-auto-continue/* to adamlui/chatgpt-auto-continue/*, then chatgpt-auto-continue/greasemonkey/* to adamlui/userscripts/chatgpt/chatgpt-auto-continue/*

on:
  push:
    branches: [main]
    paths: [chatgpt-auto-continue/**]

jobs:
  build:
    if: (github.repository == 'adamlui/chatgpt-apps') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_NAME: ${{ github.event.commits[0].author.name }}
      GIT_AUTHOR_EMAIL: ${{ github.event.commits[0].author.email }}
      GIT_COMMITTER_NAME: kudo-sync-bot
      GIT_COMMITTER_EMAIL: auto-sync@kudoai.com

    steps:

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps
          fetch-depth: 2

      - name: Checkout adamlui/chatgpt-auto-continue
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-auto-continue
          path: adamlui/chatgpt-auto-continue

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Sync _locales/* between chatgpt-auto-continue/<chrome|firefox>/extension/
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-auto-continue
          ff_dir="firefox/extension/_locales"
          chrome_dir="chrome/extension/_locales"
          
          # Loop thru all lang dirs in firefox
          for locale in $(find "$ff_dir" -mindepth 1 -maxdepth 1 -type d -exec basename {} \;) ; do
              ff_file="$ff_dir/$locale/messages.json"
              chrome_file="$chrome_dir/$locale/messages.json"
              if [[ -f "$ff_file" && -f "$chrome_file" ]] ; then

                  # Get the latest commit timestamps for both files
                  ff_timestamp=$(git log -1 --format="%ct" -- "$ff_file" 2>/dev/null || echo 0)
                  chrome_timestamp=$(git log -1 --format="%ct" -- "$chrome_file" 2>/dev/null || echo 0)
          
                  # Sync the most recently updated file to the other dir
                  if [[ $ff_timestamp -gt $chrome_timestamp ]] ; then
                      cp -f "$ff_file" "$chrome_file"
                  elif [[ $chrome_timestamp -gt $ff_timestamp ]] ; then
                      cp -f "$chrome_file" "$ff_file"
                  fi
              fi
          done

      - name: Sync chatgpt-auto-continue/* to adamlui/chatgpt-auto-continue/*
        run: |
          rsync -avhr --delete --filter={'P /.*','P /eslint*','P /package*.json'} \
            ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-auto-continue/ \
            ${{ github.workspace }}/adamlui/chatgpt-auto-continue/

      - name: Sync chatgpt-auto-continue/greasemonkey/* to adamlui/userscripts/chatgpt/chatgpt-auto-continue/*
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-auto-continue/greasemonkey/ \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-auto-continue/

      - name: Escape backticks in commit msg
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "ESCAPED_MSG<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MSG" | sed 's/`/\`/g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Push changes to adamlui/chatgpt-apps
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-apps
          git pull # again to sync w/ concurrent workflow updates
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`adamlui/chatgpt-apps\`]" || true
          git push

      - name: Push changes to adamlui/chatgpt-auto-continue
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-auto-continue
          git pull # again to sync w/ concurrent workflow updates
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`adamlui/chatgpt-apps\`]" || true
          git push

      - name: Push changes to adamlui/userscripts
        run: |
          cd ${{ github.workspace }}/adamlui/userscripts
          git pull # again to sync w/ concurrent workflow updates
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`adamlui/chatgpt-apps/chatgpt-auto-continue\`]" || true
          git push
