name: Sync LICENSE.md from chatgpt-infinity/opera/* to <platform>/*, then chatgpt-infinity/opera/extension/* to chatgpt-infinity/(chrome|edge)/extension/*, then chatgpt-infinity/opera/extension/_locales/* to chatgpt-infinity/greasemonkey/_locales/*, then chatgpt-infinity/* to adamlui/chatgpt-apps/chatgpt-infinity/*, then chatgpt-infinity/greasemonkey/* to adamlui/userscripts/chatgpt/chatgpt-infinity/*

on:
  push:
    branches: main
    paths: chatgpt-infinity/opera/**

jobs:
  build:
    if: (github.repository == 'adamlui/chatgpt-apps') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    steps:

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps
          fetch-depth: 2

      - name: Checkout adamlui/chatgpt-infinity
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-infinity
          path: adamlui/chatgpt-infinity

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Sync LICENSE.md from chatgpt-infinity/opera/* to chatgpt-infinity/<platform>/*
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-infinity
          platforms=($(find . -type d -name "docs" | # paths to docs/
            awk -F'/' '{print $(NF-1)}' | # filter to parents
            grep -v "^opera$")) # exclude opera
          echo "Platforms: ${platforms[@]}"
          languages=($(ls docs/*/LICENSE.md | # paths to LICENSEs
            awk -F'/' '{print $(NF-1)}') # filter to parents
            "en") # include English
          echo -e "Languages: ${languages[@]}\n"
          for lang in "${languages[@]}"; do
            opera_license=./opera$([[ "$lang" != "en" ]] && echo "/docs/$lang/" || echo "/")LICENSE.md
            opera_license_content=$(git show HEAD:"$opera_license")
            opera_license_modified=$(git log -1 --format="%ct" -- "$opera_license")
            for platform in "${platforms[@]}"; do
              platform_license=./$platform/$([[ "$lang" != "en" ]] && echo "docs/$lang/" || echo "")LICENSE.md
              platform_license_content=$(git show HEAD:"$platform_license")
              platform_license_modified=$(git log -1 --format="%ct" -- "$platform_license")
              if [[ $opera_license_modified -gt $platform_license_modified ]] ; then
                if [[ "$opera_license_content" != "$platform_license_content" ]] ; then
                  cp -f "$opera_license" "$platform_license"
                  echo "Copied $opera_license to $platform_license"
          fi ; fi ; done; done

      - name: Sync chatgpt-infinity/opera/extension/* to chatgpt-infinity/(chrome|edge)/extension/*
        run: |
          for browser in chrome edge
          do
            rsync -avhr --delete \
              "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-infinity/opera/extension/" \
              "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-infinity/$browser/extension/"
          done

      - name: Sync chatgpt-infinity/opera/extension/_locales/* to chatgpt-infinity/greasemonkey/_locales/*
        run: |
          rsync -avhr --delete \
            "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-infinity/opera/extension/_locales/" \
            "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-infinity/greasemonkey/_locales"

      - name: Sync chatgpt-infinity/* to adamlui/chatgpt-infinity/*
        run: |
          rsync -avhr --delete --filter={'P /.*','P /package*.json'} \
            ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-infinity/ \
            ${{ github.workspace }}/adamlui/chatgpt-infinity/

      - name: Sync chatgpt-infinity/greasemonkey/* to adamlui/userscripts/chatgpt/chatgpt-infinity/*
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-infinity/greasemonkey/ \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-infinity/

      - name: Push to adamlui/chatgpt-apps
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: --force
          add_options: --all
          commit_user_email: auto-sync@kudoai.com
          commit_message: "${{ github.event.head_commit.message }} ↞ [auto-sync from `chatgpt-infinity/opera`]"
          file_pattern: "chatgpt-infinity/**"
          repository: adamlui/chatgpt-apps

      - name: Push to adamlui/chatgpt-infinity
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: --force
          add_options: --all
          commit_user_email: auto-sync@kudoai.com
          commit_message: "${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/chatgpt-apps`]"
          file_pattern: "**"
          repository: adamlui/chatgpt-infinity

      - name: Push to adamlui/userscripts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: --force
          add_options: --all
          commit_user_email: auto-sync@kudoai.com
          commit_message: "${{ github.event.head_commit.message }} ↞ [auto-sync from `adamlui/chatgpt-apps`]"
          file_pattern: "chatgpt/chatgpt-infinity/**"
          repository: adamlui/userscripts
