name: Sync LICENSE.md from chatgpt-infinity/greasemonkey/* to <platform>/*, then chatgpt-infinity/greasemonkey/* to adamlui/userscripts/chatgpt/chatgpt-infinity/*, then chatgpt-infinity/greasemonkey/_locales/* to chatgpt-infinity/(chrome|edge|opera)/extension/_locales/*, then chatgpt-infinity/* to adamlui/chatgpt-apps/chatgpt-infinity/*

on:
  push:
    branches: [main]
    paths: [chatgpt-infinity/greasemonkey/**]

jobs:
  build:
    if: (github.repository == 'adamlui/chatgpt-apps') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_NAME: ${{ github.event.commits[0].author.name }}
      GIT_AUTHOR_EMAIL: ${{ github.event.commits[0].author.email }}
      GIT_COMMITTER_NAME: kudo-sync-bot
      GIT_COMMITTER_EMAIL: auto-sync@kudoai.com

    steps:

      - name: Checkout adamlui/chatgpt-apps
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-apps
          path: adamlui/chatgpt-apps
          fetch-depth: 2

      - name: Checkout adamlui/chatgpt-infinity
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/chatgpt-infinity
          path: adamlui/chatgpt-infinity

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Sync LICENSE.md from greasemonkey/* to <platform>/*
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-infinity
          platforms=($(find . -type d -name "docs" | # paths to docs/
            awk -F'/' '{print $(NF-1)}' | # filter to parents
            grep -v "^greasemonkey$")) # exclude greasemonkey
          echo "Platforms: ${platforms[@]}"
          languages=($(ls docs/*/LICENSE.md | # paths to LICENSEs
            awk -F'/' '{print $(NF-1)}') # filter to parents
            "en") # include English
          echo -e "Languages: ${languages[@]}\n"
          for lang in "${languages[@]}"; do
            gm_license=./greasemonkey$([[ "$lang" != "en" ]] && echo "/docs/$lang/" || echo "/")LICENSE.md
            gm_license_content=$(git show HEAD:"$gm_license")
            gm_license_modified=$(git log -1 --format="%ct" -- "$gm_license")
            for platform in "${platforms[@]}"; do
              platform_license=./$platform/$([[ "$lang" != "en" ]] && echo "docs/$lang/" || echo "")LICENSE.md
              platform_license_content=$(git show HEAD:"$platform_license")
              platform_license_modified=$(git log -1 --format="%ct" -- "$platform_license")
              if [[ $gm_license_modified -gt $platform_license_modified ]] ; then
                if [[ "$gm_license_content" != "$platform_license_content" ]] ; then
                  cp -f "$gm_license" "$platform_license"
                  echo "Copied $gm_license to $platform_license"
          fi ; fi ; done; done

      - name: Sync chatgpt-infinity/greasemonkey/* to adamlui/userscripts/chatgpt/chatgpt-infinity/*
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-infinity/greasemonkey/ \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/chatgpt-infinity/

      - name: Sync chatgpt-infinity/greasemonkey/_locales/* to chatgpt-infinity/(chrome|edge|opera)/extension/_locales/*
        run: |
          for browser in chrome edge opera
          do
            rsync -avhr --delete \
              "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-infinity/greasemonkey/_locales/" \
              "${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-infinity/$browser/extension/_locales/"
          done

      - name: Sync chatgpt-infinity/* to adamlui/chatgpt-infinity/*
        run: |
          rsync -avhr --delete --filter={'P /.*','P /eslint*','P /package*.json'} \
            ${{ github.workspace }}/adamlui/chatgpt-apps/chatgpt-infinity/ \
            ${{ github.workspace }}/adamlui/chatgpt-infinity/

      - name: Escape backticks in commit msg
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "ESCAPED_MSG<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MSG" | sed 's/`/\`/g' >> $GITHUB_ENV 
          echo "EOF" >> $GITHUB_ENV

      - name: Push changes to adamlui/chatgpt-apps
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-apps
          git pull # again to sync w/ concurrent workflow updates
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`chatgpt-infinity/greasemonkey\`]" || true
          git push

      - name: Push changes to adamlui/chatgpt-infinity
        run: |
          cd ${{ github.workspace }}/adamlui/chatgpt-infinity
          git pull # again to sync w/ concurrent workflow updates
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`adamlui/chatgpt-apps/chatgpt-infinity/greasemonkey\`]" || true
          git push

      - name: Push changes to adamlui/userscripts
        run: |
          cd ${{ github.workspace }}/adamlui/userscripts
          git pull # again to sync w/ concurrent workflow updates
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`adamlui/chatgpt-apps/chatgpt-infinity/greasemonkey\`]" || true
          git push
