name: Sync bravegpt/ to KudoAI/bravegpt/, then bravegpt/greasemonkey/ to adamlui/userscripts/chatgpt/bravegpt/

on:
  push:
    branches: [main]
    paths: [bravegpt/**]

jobs:
  build:
    if: (github.repository == 'adamlui/ai-apps') && (github.event.commits[0].committer.username != 'kudo-sync-bot')
    runs-on: ubuntu-latest
    env:
      TZ: PST8PDT

    steps:

      - name: Checkout adamlui/ai-apps
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/ai-apps
          path: adamlui/ai-apps

      - name: Checkout KudoAI/bravegpt
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: KudoAI/bravegpt
          path: KudoAI/bravegpt

      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      - name: Sync docs between root & greasemonkey/
        run: |
          shopt -s globstar
          cd ${{ github.workspace }}/adamlui/ai-apps/bravegpt
          loc_prefixes=( "root" "gm" )

          # Sync LICENSE.md
          for prefix in "${loc_prefixes[@]}" ; do
            eval "${prefix}_license_content=\$(git show HEAD:\"./\$([[ \$prefix == \"gm\" ]] && echo \"greasemonkey/\" || echo \"\")LICENSE.md\")"
            eval "${prefix}_license_modified=\$(git log -1 --format=\"%ct\" -- \"\$([[ \$prefix == \"gm\" ]] && echo \"greasemonkey/\" || echo \"\")LICENSE.md\")"
          done
          if (( root_license_modified > gm_license_modified )) ; then
            if [[ "$root_license_content" != "$gm_license_content" ]] ; then
              cp -f "LICENSE.md" "greasemonkey/LICENSE.md" ; sync_src="root" ; fi
          elif (( gm_license_modified > root_license_modified )) ; then
            if [[ "$gm_license_content" != "$root_license_content" ]] ; then
              cp -f "greasemonkey/LICENSE.md" "LICENSE.md" ; sync_src="greasemonkey" ; fi ; fi

          # Sync other docs
          for file in docs/**/*.md ; do
            for prefix in "${loc_prefixes[@]}" ; do
              eval "${prefix}_doc_path=\"./\$([[ \$prefix == \"gm\" ]] && echo \"greasemonkey/\" || echo \"\")docs/${file#"docs/"}\""
              eval "${prefix}_doc_content=\$(git show HEAD:\"\$${prefix}_doc_path\")"
              eval "${prefix}_doc_modified=\$(git log -1 --format=\"%ct\" -- \"\$${prefix}_doc_path\")"
            done
            if (( root_doc_modified > gm_doc_modified )) ; then
              if [[ "$root_doc_content" != "$gm_doc_content" ]] ; then
                cp -f "$root_doc_path" "$gm_doc_path" ; sync_src="root" ; fi
            elif (( gm_doc_modified > root_doc_modified )) ; then
              if [[ "$gm_doc_content" != "$root_doc_content" ]] ; then
                cp -f "$gm_doc_path" "$root_doc_path" ; sync_src="greasemonkey" ; fi ; fi
          done

          # Expose sync src for commit msg in self-push step
          echo "sync_src=$sync_src" >> $GITHUB_ENV

      - name: Sync bravegpt/ to KudoAI/bravegpt/
        run: |
          rsync -avhr --delete --filter={'P /.*','P /eslint*','P /package*.json'} \
            ${{ github.workspace }}/adamlui/ai-apps/bravegpt/ \
            ${{ github.workspace }}/KudoAI/bravegpt/

      - name: Sync bravegpt/greasemonkey/ to adamlui/userscripts/chatgpt/bravegpt/
        run: |
          rsync -avhr --delete \
            ${{ github.workspace }}/adamlui/ai-apps/bravegpt/greasemonkey/ \
            ${{ github.workspace }}/adamlui/userscripts/chatgpt/bravegpt/

      - name: Escape backticks in commit msg
        env:
          COMMIT_MSG: ${{ github.event.head_commit.message }}
        run: |
          echo "ESCAPED_MSG<<EOF" >> $GITHUB_ENV
          echo "$COMMIT_MSG" | sed 's/`/\`/g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
      
      - name: Config committer
        run: |
          gpg --batch --import <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
          git config --global commit.gpgsign true
          git config --global user.name "kudo-sync-bot"
          git config --global user.email "auto-sync@kudoai.com"
          git config --global user.signingkey  "${{ secrets.GPG_PRIVATE_ID }}"

      - name: Push changes to adamlui/ai-apps
        run: |
          cd ${{ github.workspace }}/adamlui/ai-apps
          git pull # again to sync w/ concurrent workflow updates
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`${{ env.sync_src }}\`]" || true
          git push

      - name: Push changes to KudoAI/bravegpt
        run: |
          cd ${{ github.workspace }}/KudoAI/bravegpt
          git pull # again to sync w/ concurrent workflow updates
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`adamlui/ai-apps\`]" || true
          git push

      - name: Push changes to adamlui/userscripts
        run: |
          cd ${{ github.workspace }}/adamlui/userscripts
          git pull # again to sync w/ concurrent workflow updates
          git add .
          git commit -n -m "$ESCAPED_MSG ↞ [auto-sync from \`adamlui/ai-apps/bravegpt\`]" || true
          git push
